apiVersion: v2
name: task
type: application
version: 0.2.0
appVersion: "v0.3.1"
description: A Helm chart to deploy Task Manager Api.
deprecated: false
annotations: {}
keywords: []
dependencies:
  - name: rabbitmq
    version: "0.18.0"
    repository: "oci://registry-1.docker.io/cloudpirates"
    condition: rabbitmq.enabled
  - name: cnpg-cluster
    alias: cnpg
    version: "1.5.4"
    repository: "https://this-is-tobi.github.io/helm-charts"
    condition: cnpg.enabled
  - name: pgadmin4
    condition: pgadmin.enabled
    alias: pgadmin
    version: 1.59.0
    repository: https://helm.runix.net/
  - name: sql-exporter
    alias: sqlExporter
    version: "0.17.5"
    repository: "https://burningalchemist.github.io/sql_exporter/"
    condition: sqlExporter.enabled
sources:
- https://github.com/titigmr/async-api
maintainers:
 - name: titigmr
   url: https://github.com/titigmr
