include:
  - project: $CATALOG_PATH
    file:
      - vault-ci.yml
      # - buildkit-ci.yml
    ref: main

default:
    image: alpine:latest

variables:
    REGISTRY_URL: "${IMAGE_REPOSITORY}"
    DOCKERFILE: Dockerfile

stages:
  - read-secret
  - docker-build

.buildkit:build-push:
  variables:
    WORKING_DIR: "."
    DOCKERFILE_DIR: $WORKING_DIR
    DOCKERFILE_NAME: Dockerfile
    BUILDKITD_FLAGS: --oci-worker-no-process-sandbox
    CACHE_IMAGE: $REGISTRY_URL/$IMAGE_NAME:cache
    OUTPUT_IMAGES: $REGISTRY_URL/$IMAGE_NAME:$TAG
    EXTRA_BUILD_ARGS: ""
    EXTRA_BUILDKIT_ARGS: ""
  image:
    name: moby/buildkit:rootless
    entrypoint: [""]
  script:
    # CA
    - if [ ! -z $CA_BUNDLE ]; then cat $CA_BUNDLE >> ~/certs/additional-ca-cert-bundle.crt && export SSL_CERT_DIR="/home/user/certs"; fi
    # Docker Authentification
    - mkdir -p ~/.docker && echo "$DOCKER_AUTH" > ~/.docker/config.json
    # Plusieurs outputs (chaque élément = image complète registry/name:tag)
    - export OUTPUT_OPTS=""
    - for I in $OUTPUT_IMAGES; do export OUTPUT_OPTS="$OUTPUT_OPTS --output type=image,name=$I,push=true"; done
    # Build
    - |
      buildctl-daemonless.sh build \
        --frontend dockerfile.v0 \
        --opt build-arg:http_proxy=$http_proxy \
        --opt build-arg:https_proxy=$https_proxy \
        --opt build-arg:no_proxy=$no_proxy \
        --local context="$CI_PROJECT_DIR/$WORKING_DIR" \
        --local dockerfile="$CI_PROJECT_DIR/$DOCKERFILE_DIR" \
        --opt filename="$DOCKERFILE_NAME" \
        --export-cache type=registry,ref=$CACHE_IMAGE \
        --import-cache type=registry,ref=$CACHE_IMAGE \
        $OUTPUT_OPTS \
        $EXTRA_BUILD_ARGS \
        $EXTRA_BUILDKIT_ARGS

read_secret:
  stage: read-secret
  only:
    - tags
  extends:
    - .vault:read_secret

docker-build:async-api:
  stage: docker-build
  needs: ["read_secret"]
  only:
    - tags
  variables:
    WORKING_DIR: .
    IMAGE_NAME: async-api
    TAG: "${CI_COMMIT_TAG}"
  extends:
    - .buildkit:build-push

docker-build:consumer:
  stage: docker-build
  needs: ["read_secret"]
  only:
    - tags
  variables:
    WORKING_DIR: ./workers/js
    DOCKERFILE_NAME: Dockerfile
    IMAGE_NAME: async-api-consumer
    TAG: "${CI_COMMIT_TAG}"
  extends:
    - .buildkit:build-push

docker-build:generation-render:
  stage: docker-build
  needs: ["read_secret"]
  only:
    - tags
  variables:
    WORKING_DIR: ./workers/python/generation-render
    DOCKERFILE_NAME: Dockerfile
    IMAGE_NAME: generation-render-worker
    TAG: "${CI_COMMIT_TAG}"
  extends:
    - .buildkit:build-push