include:
  - project: $CATALOG_PATH
    file:
      - vault-ci.yml
      - kaniko-ci.yml
    ref: main

default:
    image: alpine:latest

variables:
    REGISTRY_URL: "${IMAGE_REPOSITORY}"
    DOCKERFILE: Dockerfile

stages:
  - read-secret
  - docker-build

read_secret:
  only:
    - tags
  stage: read-secret
  extends:
    - .vault:read_secret

docker-build:async-api:
  needs: ["read_secret"]
  only:
    - tags
  variables:
    WORKING_DIR: "."
    IMAGE_NAME: async-api
    TAG: "${CI_COMMIT_TAG}"
  stage: docker-build
  extends:
    - .kaniko:simple-build-push

docker-build:consumer:
  needs: ["read_secret"]
  only:
    - tags
  variables:
    WORKING_DIR: "workers/js"
    DOCKERFILE: Dockerfile-ci
    IMAGE_NAME: async-api-consumer
    TAG: "${CI_COMMIT_TAG}"
  stage: docker-build
  extends:
    - .kaniko:simple-build-push