include:
  - project: $CATALOG_PATH
    file:
      - vault-ci.yml
      - buildkit-ci.yml
    ref: main

default:
    image: alpine:latest

variables:
    REGISTRY_URL: "${IMAGE_REPOSITORY}"
    DOCKERFILE: Dockerfile

stages:
  - read-secret
  - docker-build

read_secret:
  stage: read-secret
  only:
    - tags
  extends:
    - .vault:read_secret

docker-build:async-api:
  stage: docker-build
  needs: ["read_secret"]
  only:
    - tags
  variables:
    WORKING_DIR: .
    IMAGE_NAME: async-api
    TAG: "${CI_COMMIT_TAG}"
  extends:
    - .buildkit:build-push

docker-build:consumer:
  stage: docker-build
  needs: ["read_secret"]
  only:
    - tags
  variables:
    WORKING_DIR: ./workers/js
    DOCKERFILE_NAME: Dockerfile
    IMAGE_NAME: async-api-consumer
    TAG: "${CI_COMMIT_TAG}"
  extends:
    - .buildkit:build-push

docker-build:generation-render:
  stage: docker-build
  needs: ["read_secret"]
  only:
    - tags
  variables:
    WORKING_DIR: ./workers/python/generation-render
    DOCKERFILE_NAME: Dockerfile
    IMAGE_NAME: generation-render-worker
    TAG: "${CI_COMMIT_TAG}"
  extends:
    - .buildkit:build-push