{{- if .Files.Get "config/services.yaml" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-%s" (include "helper.fullname" .) "services-config" }}
  labels:
    {{- include "helper.labels" (dict "root" . "componentName" "config") | nindent 4 }}
    app.kubernetes.io/component: configuration
    async-api.io/config-type: services
data:
  services.yaml: |
{{ .Files.Get "config/services.yaml" | indent 4 }}
{{- end -}}
