{{- if .Values.vaultSecrets.enabled -}}
{{- $labels := (include "helper.labels" (dict "root" . "componentName" "api")) -}}
{{ range $secret := .Values.vaultSecrets.items }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ $secret.destination.name }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  mount: {{ $secret.mount }}
  path: {{ $secret.vaultPath }}
  type: kv-v2
  vaultAuthRef: vault-auth
  destination:
    create: true
    name: {{ $secret.destination.name }}
    type: {{ $secret.destination.type }}
{{- end -}}
{{- end -}}