name: Trigger CPiN sync

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  path-filter:
    runs-on: ubuntu-latest
    outputs:
      charts: ${{ steps.filter.outputs.charts }}
      api: ${{ steps.filter.outputs.api }}
      ci: ${{ steps.filter.outputs.ci }}
      widgets: ${{ steps.filter.outputs.widgets }}
    steps:
    - name: Checks-out repository
      uses: actions/checkout@v4

    - name: Check updated files paths
      uses: dorny/paths-filter@v3
      id: filter
      with:
        base: main
        ref: ${{ github.ref_name }}
        filters: |
          charts:
            - 'chart/**'
          api:
            - 'api/**'
          ci:
            - '.gitlab-ci-dso.yml'
          widgets:
            - 'grist-widgets/**'

  sync:
    needs:
    - path-filter
    uses: dnum-mi/fabnum-cicd/.github/workflows/sync-cpin.yml@v0
    if: ${{ needs.path-filter.outputs.charts == 'true' || needs.path-filter.outputs.api == 'true' || needs.path-filter.outputs.ci == 'true' || needs.path-filter.outputs.widgets == 'true' }}
    with:
      GITLAB_URL: "${{ secrets.GITLAB_URL }}"
      GIT_MIRROR_PROJECT_ID: "${{ vars.GITLAB_MIRROR_ID }}"
      BRANCH_TO_SYNC: ${{ github.ref_name }}
      REPOSITORY_NAME: "${{ vars.GITLAB_PROJECT_NAME }}"
    secrets:
      GIT_MIRROR_TOKEN: ${{ secrets.GIT_MIRROR_TOKEN }}
